# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-SpreadPagination
version:      0.1
license:      perl
version_from: lib/Data/SpreadPagination.pm
installdirs:  site
requires:
    Data::Page:                    0.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21 + manual
